const database = {
  bands: [
    {
      id: 1,
      bandName: "Band1",
      members: 3,
      genre: "Rock",
      yearFormed: 1909,
    },
    {
      id: 2,
      bandName: "Band2",
      members: 8,
      genre: "Classical",
      yearFormed: 1981,
    },
    {
      id: 3,
      bandName: "Band3",
      members: 4,
      genre: "Punk",
      yearFormed: 1982,
    },
    {
      id: 4,
      bandName: "Band4",
      members: 2,
      genre: "Mellow",
      yearFormed: 1985,
    },
    {
      id: 5,
      bandName: "Band5",
      members: 5,
      genre: "Rap",
      yearFormed: 1859,
    },
    {
      id: 6,
      bandName: "Band6",
      members: 7,
      genre: "Techno",
      yearFormed: 2011,
    },
    {
      id: 7,
      bandName: "Band7",
      members: 3,
      genre: "Jazz",
      yearFormed: 2023,
    },
    {
      id: 8,
      bandName: "Band8",
      members: 4,
      genre: "Polka",
      yearFormed: 1901,
    },
    {
      id: 9,
      bandName: "Band9",
      members: 3,
      genre: "EDM",
      yearFormed: 1932,
    },
    {
      id: 10,
      bandName: "Band10",
      members: 4,
      genre: "Country",
      yearFormed: 1920,
    },
  ],
  venues: [
    {
      id: 1,
      venueName: "Oak",
      address: "121 Craft Street",
      squareFootage: 1000,
      maxOccupancy: 100,
    },
    {
      id: 2,
      venueName: "WhiteOak",
      address: "400 Sawyer Road",
      squareFootage: 1200,
      maxOccupancy: 250,
    },
    {
      id: 3,
      venueName: "Pine",
      address: "250 Inka blvd",
      squareFootage: 2000,
      maxOccupancy: 120,
    },
    {
      id: 4,
      venueName: "Burch",
      address: "10 Lost Drive",
      squareFootage: 800,
      maxOccupancy: 350,
    },
    {
      id: 5,
      venueName: "Twig",
      address: "45 Fox Street",
      squareFootage: 900,
      maxOccupancy: 800,
    },
  ],
  bookings: [
    {
      id: 1,
      bandID: 1 && 3,
      venueID: 5,
      dateBooked: "09/01/203",
    },
    {
      id: 2,
      bandID: 5 && 7,
      venueID: 1,
      dateBooked: "12/11/1985",
    },
    {
      id: 3,
      bandID: 9 && 2,
      venueID: 3,
      dateBooked: "11/01/2024",
    },
    {
      id: 4,
      bandID: 4 && 6,
      venueID: 4,
      dateBooked: "03/05/2024",
    },
    {
      id: 5,
      bandID: 8 && 10,
      venueID: 2,
      dateBooked: "07/15/2024",
    },
  ],
};
